development:
  GMAIL_USERNAME: myemail@gmail.com
  GMAIL_PASSWORD: mypassword
production:
  GMAIL_USERNAME: myemail@mydomain.com
  GMAIL_PASSWORD: myproductionpassword
test:
  GMAIL_USERNAME: myemail@gmail.com
  GMAIL_PASSWORD: mypassword
